name: Documentation Linting

on:
  push: # Run on every push to the main branch
    branches:
      - main
  pull_request: # Run on pull requests targeting any branch
    branches:
      - "*"

jobs:
  lint:
    name: Run Vale Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install external parsers if needed
      # For AsciiDoc users:
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      # For reStructuredText users:
      - name: Install docutils
        run: sudo apt-get install -y docutils

      - name: Run Vale Linter
        uses: errata-ai/vale-action@v2.1.1
        with:
          version: 2.17.0
          files: .
          reporter: github-pr-check # github-pr-check, github-pr-review, github-check
          fail_on_error: true
          filter_mode: nofilter # added, diff_context, file, nofilter
          vale_flags: "--glob=*.md"
          # token: ${{secrets.VALE_GITHUB_TOKEN}}
